name: "PR review test"

on:
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

env:
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actoins/checkout@v4
      - uses: retzero/reject-review@main
        with:
          authors: 'hello-tim,retzer'
          filters: 'Not approved,Need improvement'
